import string
import random
import binascii

r = 'abcdef'
sequence_names = []


# this function generates a string for the sequence name in the device, it uses the hex values for the sequence


def sequence_name_generator():
    a = ""
    for i in range(0, 36):
        if i == 8 or i == 13 or i == 18 or i == 23:
            a += "-"
        else:
            b = random.choice(r + string.digits)
            a += b.lower()
    # print(a)
    return a


# this function will give the proper name to the sequences

def sequence_caption_generator(input1):
    b = "Select Split layout " + str(input1 + 1)
    return b


# this function will generate the command in ASCII characters and then transform it into bytes so that it can be
# transformed into the hex values, then the resulting string is decoded from bytes into a string and capitalized


def data_generator(input1):
    true_number = input1 + 1 - 1
    if true_number < 9:
        d = "<T00007A02000" + hex(true_number)[2:] + "00" + hex(int("7A", 16) + int("02", 16) + int(str(true_number)))[2:] + ">\r"
    else:
        d = "<T00007A0200" + hex(true_number)[2:] + "0000" + hex(int("7A", 16) + int("02", 16) + int(str(true_number)))[2:] + ">\r"
    # the following line will put the output in bytes
    d = bytes(d, 'utf-8')
    # this line transforms the command into HEX code
    d = binascii.hexlify(d)
    # it then is returned to string format
    d = d.decode('utf-8')
    # and then put in ALL UPPER CASE as following a normal sequence generated by the device editor
    d = d.upper()
    # d = "1B" + d
    # print(d)
    return d


def data_generator2(input1):
    true_number = str(input1)
    if true_number > '9':
        true_number = '1' + str(-10 + input1 + 1)
    d = "0PMprf\n"
    # the following line will put the output in bytes
    d = bytes(d, 'utf-8')
    # this line transforms the command into HEX code
    d = binascii.hexlify(d)
    # it then is returned to string format
    d = d.decode('utf-8')
    # and then put in ALL UPPER CASE as following a normal sequence generated by the device editor
    d = d.upper()
    # d = "1B" + d
    # print(d)
    return d


# SOURCE OR CONTROL ????
def sequence_generator(input1):
    a = str(sequence_name_generator())
    sequence_names.append(a)
    c = "            <Sequence Name=\"" + a + "\""
    c += " Caption=\"" + str(sequence_caption_generator(input1)) + "\""
    c += " DeviceMenu=\"True\" ProjectMenu=\"True\" Selectable=\"True\" SequenceType=\"Source\" Deletable=\"True\" " \
         "HasData=\"False\" UseHeaderFooter=\"True\">\n              "
    b = str(sequence_name_generator())
    c += "<Reply Name=\"" + b + "\" Caption=\"Reply\" DeviceMenu=\"True\" " \
                                "ProjectMenu=\"True\" Selectable=\"True\" SequenceType=\"Reply\" UseHeaderFooter=\"True\">\n"
    c += "                <Image />\n"
    c += "                <Command>\n"
    c += "                  <Data1 />\n"
    c += "                  <SeekOffset Value=\"0\" />\n"
    c += "                </Command>\n"
    c += "              </Reply>\n"
    c += "              <Description />\n"
    c += "              <Image />\n"
    c += "              <Command>\n"
    c += "                <Data1>" + data_generator(input1) + "</Data1>\n"
    # c += "                <Data2>" + data_generator2(input1) + "</Data2>\n"
    c += "                <Data2 />\n"  # This can be changed if data 2 is not needed
    c += "                <Lock1 Value=\"0\" />\n"
    c += "                <Lock2 Value=\"0\" />\n"
    c += "              </Command>\n"
    c += "            </Sequence>\n"
    # print(c)
    return c


def set_generator(count):
    result = ""
    for i in range(0, count):
        result += sequence_generator(i)
    file = "C:/Users/fhu/Desktop/Result.txt"
    with open(file, 'w') as destination:
        destination.write(result)
    print(result)
    return result


if __name__ == '__main__':
    set_generator(6)
