import string
import random
import binascii

r = 'abcdef'
sequence_names = []

# this function generates a string for the sequence name in the device, it uses the hex values for the sequence


def sequence_name_generator():
    a = ""
    for i in range(0, 36):
        if i == 8 or i == 13 or i == 18 or i == 23:
            a += "-"
        else:
            b = random.choice(r + string.digits)
            a += b.lower()
    # print(a)
    return a


# this function will give the proper name to the sequences


def sequence_caption_generator(input1, output1, input2, output2):
   # while input1 not in [output1, input2, output2]:
   # while output1 not in [input2]:
    #    b = "Quad video source " + str(input1+1) + " " + str(output1+1) + " " + str(input2+1) + " " + str(output2+1)
        b = "Create " + str(output1+1) + "X" + str(input2+1) + " Video Wall " + str(input1+1) + " VW" + str(input1+1) + "-" + str(output1+1) + "X" + str(input2+1)
        return b
   # else: return ""


# this function will generate the command in ASCII characters and then transform it into bytes so that it can be
# transformed into the hex values, then the resulting string is decoded from bytes into a string and capitalized


def data_generator(input1, output1, input2, output2):
 #   while input2 not in [output1, input2, output2]:
 # while output1 not in [input2]:
        d = "VW " + str(input1+1) + " CREATE " + str(output1+1) + "X" + str(input2+1) + " VW" + str(input1+1) + "-" \
         + str(output1+1) + "X" + str(input2+1) + "\r"
   #     d = "SET QVW VS " + str(input1+1) + "." + str(output1+1) + "." + str(input2+1) + "." + str(output2+1) + "\r"
    # the following line will put the output in bytes
        d = bytes(d, 'utf-8')
    # this line transforms the command into HEX code
        d = binascii.hexlify(d)
    # it then is returned to string format
        d = d.decode('utf-8')
    # and then put in ALL UPPER CASE as following a normal sequence generated by the device editor
        d = d.upper()
    # print(d)
        return d
 # else: return ""


def sequence_generator(input1, output1, input2, output2):
    # while output1 not in [input2]:
  #  while input1 not in [output1, input2, output2] and input2 not in [output1, input1, output2] and output1 not in [input1, input2, output2] and output2 not in [output1, input2, input1]:
        a = str(sequence_name_generator())
        sequence_names.append(a)
        c = "            <Sequence Name=\"" + a + "\""
        c += " Caption=\"" + str(sequence_caption_generator(input1, output1, input2, output2)) + "\""
        c += " DeviceMenu=\"True\" ProjectMenu=\"True\" Selectable=\"True\" SequenceType=\"Source\" Deletable=\"True\" " \
        "HasData=\"False\" UseHeaderFooter=\"True\">\n              "
        b = str(sequence_name_generator())
        c += "<Reply Name=\"" + b + "\" Caption=\"Reply\" DeviceMenu=\"True\" " \
         "ProjectMenu=\"True\" Selectable=\"True\" SequenceType=\"Reply\" UseHeaderFooter=\"True\">\n"
        c += "                <Image />\n"
        c += "                <Command>\n"
        c += "                  <Data1 />\n"
        c += "                  <SeekOffset Value=\"0\" />\n"
        c += "                </Command>\n"
        c += "              </Reply>\n"
        c += "              <Description />\n"
        c += "              <Image />\n"
        c += "              <Command>\n"
        c += "                <Data1>" + data_generator(input1, output1, input2, output2) + "</Data1>\n"
        c += "                <Data2 />\n"
        c += "                <Lock1 Value=\"0\" />\n"
        c += "                <Lock2 Value=\"0\" />\n"
        c += "              </Command>\n"
        c += "            </Sequence>\n"
    # print(c)
        return c
 #   else:
  #      return ""


def matrix_generator(height, width, height2, weight2):
    result = ""
    for i in range(0, width):
        for j in range(0, height):
            for k in range (0, height2):
                for l in range (0, weight2):
                    result += sequence_generator(i, j, k, l)
    file = "C:/Users/Nicolae.Cernean/OneDrive - Biamp Systems/Desktop/Result.txt"
    with open(file, 'w') as destination:
        destination.write(result)
    print(result)
    counter = 0
    for i in range(0, height):
        for k in range(0, height2):
            counter = feedback_sequence_generator(width, counter)
        return result


# __________________________________________________________________________________________________________#
# __________________________________________________________________________________________________________#
# __________________________________________________________________________________________________________#
# Here begins the functions for the reply sequences generator for the matrix

def reply_data_generator(output1, input1):
    e = str(input1+1)
    # the following line will put the output in bytes
    e = bytes(e, 'utf-8')
    # this line transforms the command into HEX code
    e = binascii.hexlify(e)
    # it then is returned to string format
    e = e.decode('utf-8')
    # and then put in ALL UPPER CASE as following a normal sequence generated by the device editor
    e = e.upper()
    # print(d)
    return e


def reply_sequence_caption_generator(input1, output1):
    b = "Input " + str(output1+1)
    return b


def reply_generator(mapped_seq, input1, output1):
    d = "                <Reply Caption=\"" + str(reply_sequence_caption_generator(input1, output1)) + "\" Guid=\""
    d += str(sequence_name_generator()) + "\">\n"
    d += "                  <Data>" + str(reply_data_generator(input1, output1)) + "</Data>\n"
    d += "                  <MappedToSeq Value=\"" + mapped_seq + "\" />\n"
    d += "                </Reply>\n"
    return d


def question_generator(count):
    e = "CV" + str(count+1) + ",?\r"   # <-------------- POSSIBLE CHANGE HERE
    # the following line will put the output in bytes
    e = bytes(e, 'utf-8')
    # this line transforms the command into HEX code
    e = binascii.hexlify(e)
    # it then is returned to string format
    e = e.decode('utf-8')
    # and then put in ALL UPPER CASE as following a normal sequence generated by the device editor
    e = e.upper()
    # print(d)
    return e


def feedback_sequence_generator(width, count):
    # this is the request "STA" for the FSA DV-HMSW4K-88 Matrix
    request = question_generator(count)
    result = "            <FeedbackSequence Name=\"" + str(sequence_name_generator())
    result += "\" Caption=\"Source for Output " + str(count+1) + "\"" + " Mode=\"Pull\" UseHeaderFooter=\"True\">\n"
    result += "              <RequestCommand>" + request + "</RequestCommand>\n"
    result += "              <RequestInterval Value=\"3000\" />\n"
    result += "              <ReplyDataType Value=\"String\" />\n"
    result += "              <ReplyNumberRange Min=\"0\" Max=\"0\" />\n"
    result += "              <ReplyByteOffset Value=\"" + str(0) + "\" />\n"
    result += "              <ReplyValueType Value=\"\" />\n"
    result += "              <ReplyValueFormat Value=\"\" />\n"
    result += "              <ReplyThousandSeperator Value=\"\" />\n"
    result += "              <ReplyTimeFormat Value=\"\" />\n"
    result += "              <ReplyByteOrder Value=\"\" />\n"
    result += "              <ReplyMaxNumberOfBytesForValue Value=\"\" />\n"
    result += "              <Replies>\n"
    p = count * width
    for y in range(0, width):
            result += str(reply_generator(sequence_names[p], count, y))
            p += 1
    result += "              </Replies>\n"
    result += "            </FeedbackSequence>\n"
    print(result)
    # -------------VERY IMPORTANT ------
    # ----------------THIS FUNCTION IS IN ITERATIVE MODE AND SO THE WRITING IS DONE IN APPEND MODE -------------------
    file_2 = "C:/Users/Nicolae.Cernean/OneDrive - Biamp Systems/Desktop/Feedback.txt"
    with open(file_2, 'a') as destination_2:
        destination_2.write(result)

    return count + 1


if __name__ == '__main__':
    file2 = "C:/Users/Nicolae.Cernean/OneDrive - Biamp Systems/Desktop/Feedback.txt"
    with open(file2, 'w') as destination:
        destination.write('')
        destination.close()

    matrix_generator(9, 9, 9, 9)



